-- AlterTable
ALTER TABLE "product_reports" ADD COLUMN     "ad_spend_rate" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "roas" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "total_ad_spend" DOUBLE PRECISION NOT NULL DEFAULT 0;
